# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yakmv < Formula
  desc "Kubernetes manifest validator"
  homepage "https://github.com/doodlescheduling/yakmv"
  version "0.0.12"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DoodleScheduling/yakmv/releases/download/v0.0.12/yakmv_0.0.12_darwin_arm64.tar.gz"
      sha256 "a00d9b4b37973a9fed181c8532365b653ab32ec36cf35bd88c1bee81971916f5"

      def install
        bin.install "yakmv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/yakmv/releases/download/v0.0.12/yakmv_0.0.12_darwin_amd64.tar.gz"
      sha256 "3fb849f256ff1e92060832b68ad9dcb51e05c40a384aeefb36f5ad6107845daf"

      def install
        bin.install "yakmv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoodleScheduling/yakmv/releases/download/v0.0.12/yakmv_0.0.12_linux_arm64.tar.gz"
      sha256 "41bd54f35ceed4bf9a2fd23490e378c2914f9b0c459bf8281d17941c4eab16ae"

      def install
        bin.install "yakmv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/yakmv/releases/download/v0.0.12/yakmv_0.0.12_linux_amd64.tar.gz"
      sha256 "29b26757653f93cb40251fcda935534b742ae3aa73ff0512491b0088c398804a"

      def install
        bin.install "yakmv"
      end
    end
  end

  test do
    system "#{bin}/yakmv -h"
  end
end
