# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yakmv < Formula
  desc "Kubernetes manifest validator"
  homepage "https://github.com/doodlescheduling/yakmv"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/yakmv/releases/download/v0.0.9/yakmv_0.0.9_darwin_amd64.tar.gz"
      sha256 "bcdaa10b762096b22efae5cd91e1e0e46e5ac8298b18fc6090a9ab8ae4985483"

      def install
        bin.install "yakmv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DoodleScheduling/yakmv/releases/download/v0.0.9/yakmv_0.0.9_darwin_arm64.tar.gz"
      sha256 "369035f2a20beb31eaa77ca0e72f94397f1e9771a751c438fd1c84ff919099b8"

      def install
        bin.install "yakmv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoodleScheduling/yakmv/releases/download/v0.0.9/yakmv_0.0.9_linux_arm64.tar.gz"
      sha256 "baac229289419f1079e8c32c2bded63fcd152a26426001b14d7ca5dbd954fcdc"

      def install
        bin.install "yakmv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/yakmv/releases/download/v0.0.9/yakmv_0.0.9_linux_amd64.tar.gz"
      sha256 "d86abd7cacaf95c332b14f981e59ca6e9fd14cfd0d4abd5226d9b8d22fd6aabb"

      def install
        bin.install "yakmv"
      end
    end
  end

  test do
    system "#{bin}/yakmv -h"
  end
end
