# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yakmv < Formula
  desc "Kubernetes manifest validator"
  homepage "https://github.com/doodlescheduling/yakmv"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/yakmv/releases/download/v0.0.1/yakmv_0.0.1_darwin_amd64.tar.gz"
      sha256 "128db02de1d028829b9c84f356291389394199daf0a7f98f939b084cb1072aa0"

      def install
        bin.install "yakmv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DoodleScheduling/yakmv/releases/download/v0.0.1/yakmv_0.0.1_darwin_arm64.tar.gz"
      sha256 "5a938529fec3687f82ea6f1c39b8228b674e09d96e4a0e530ed283c4720d776a"

      def install
        bin.install "yakmv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoodleScheduling/yakmv/releases/download/v0.0.1/yakmv_0.0.1_linux_arm64.tar.gz"
      sha256 "0c666e1b70f9a26d721e8540284ba5759ab24f5d3a19c4942f23b658fb1d2631"

      def install
        bin.install "yakmv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/yakmv/releases/download/v0.0.1/yakmv_0.0.1_linux_amd64.tar.gz"
      sha256 "580ec84ad0fa06f3a75121052a79c43da889a54209beb30c94b5ae66121ff498"

      def install
        bin.install "yakmv"
      end
    end
  end

  test do
    system "#{bin}/yakmv -h"
  end
end
